config/routes.rb
TaxiComentarios::Application.routes.draw do
  resources :comentarios

  resources :placas

end

app/models/comentario.rb
class Comentario < ActiveRecord::Base
  validates :coment, presence: true
  belongs_to :placa
  default_scope -> { order('created_at DESC') }
end

app/models/placa.rb
class Placa < ActiveRecord::Base
  has_many :comentarios, dependent: :destroy
  validates_uniqueness_of :numero
  validates_format_of :numero, :without => /\A\d/

  def to_param
    numero
  end

  def self.find(numero)
    numero.to_i == 0 ? find_by(numero: numero) : super
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  before_action :set_comentario, only: [:show, :edit, :update, :destroy]
  protect_from_forgery with: :null_session, :if => Proc.new { |c| c.request.format == 'application/json' }

  # GET /comentarios
  # GET /comentarios.json
  def index
    @comentarios = Comentario.all
  end

  # GET /comentarios/1
  # GET /comentarios/1.json
  def show
  end

  # GET /comentarios/new
  def new
    @comentario = Comentario.new
  end

  # GET /comentarios/1/edit
  def edit
  end

  # POST /comentarios
  # POST /comentarios.json
  def create
    placa = nil
    if placa = Placa.find_by(numero: params[:comentario][:placa] )
    else
      placa = Placa.create(numero: params[:comentario][:placa])
    end
    puts placa
    @comentario = placa.comentarios.build(comentario_params)

    respond_to do |format|
      if @comentario.save
        format.html { redirect_to @comentario, notice: 'Comentario was successfully created.' }
        format.json { render action: 'show', status: :created, location: @comentario }
      else
        format.html { render action: 'new' }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comentarios/1
  # PATCH/PUT /comentarios/1.json
  def update
    respond_to do |format|
      if @comentario.update(comentario_params)
        format.html { redirect_to @comentario, notice: 'Comentario was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comentarios/1
  # DELETE /comentarios/1.json
  def destroy
    @comentario.destroy
    respond_to do |format|
      format.html { redirect_to comentarios_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comentario
      @comentario = Comentario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comentario_params
      params.require(:comentario).permit(:coment, :usuario, :buen_comentario)
    end
end

app/controllers/placas_controller.rb
class PlacasController < ApplicationController
  before_action :set_placa, only: [:show, :edit, :update, :destroy]

  # GET /placas
  # GET /placas.json
  def index
    @placas = Placa.all
  end

  # GET /placas/1
  # GET /placas/1.json
  def show
    @comentarios = @placa.comentarios
  end

  # GET /placas/new
  def new
    @placa = Placa.new
  end

  # GET /placas/1/edit
  def edit
  end

  # POST /placas
  # POST /placas.json
  def create
    @placa = Placa.new(placa_params)

    respond_to do |format|
      if @placa.save
        format.html { redirect_to @placa, notice: 'Placa was successfully created.' }
        format.json { render action: 'show', status: :created, location: @placa }
      else
        format.html { render action: 'new' }
        format.json { render json: @placa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /placas/1
  # PATCH/PUT /placas/1.json
  def update
    respond_to do |format|
      if @placa.update(placa_params)
        format.html { redirect_to @placa, notice: 'Placa was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @placa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /placas/1
  # DELETE /placas/1.json
  def destroy
    @placa.destroy
    respond_to do |format|
      format.html { redirect_to placas_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_placa
      @placa = Placa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def placa_params
      params.require(:placa).permit(:numero)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/helpers/placas_helper.rb
module PlacasHelper
end

app/views/comentarios/_comentario.html.erb
<li>
  <span class="content"><%= comentario.coment %>
  <span>|| Escrito hace <%= time_ago_in_words(comentario.created_at) %></span>
</li>

app/views/comentarios/_form.html.erb
<%= form_for(@comentario) do |f| %>
  <% if @comentario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comentario.errors.count, "error") %> prohibited this comentario from being saved:</h2>

      <ul>
      <% @comentario.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :placa %><br>
    <%= f.text_field :placa %>
  </div>
  <div class="field">
    <%= f.label :coment %><br>
    <%= f.text_area :coment %>
  </div>
  <div class="field">
    <%= f.label :usuario %><br>
    <%= f.number_field :usuario %>
  </div>
  <div class="field">
    <%= f.label :buen_comentario %>
    <%= f.check_box :buen_comentario %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comentarios/edit.html.erb
<h1>Editing comentario</h1>

<%= render 'form' %>

<%= link_to 'Show', @comentario %> |
<%= link_to 'Back', comentarios_path %>

app/views/comentarios/index.html.erb
<h1>Listing comentarios</h1>

<table>
  <thead>
    <tr>
      <th>Placa</th>
      <th>Coment</th>
      <th>Usuario</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @comentarios.each do |comentario| %>
      <tr>
        <td><%= comentario.placa %></td>
        <td><%= comentario.coment %></td>
        <td><%= comentario.usuario %></td>
        <td><%= link_to 'Show', comentario %></td>
        <td><%= link_to 'Edit', edit_comentario_path(comentario) %></td>
        <td><%= link_to 'Destroy', comentario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comentario', new_comentario_path %>

app/views/comentarios/new.html.erb
<h1>New comentario</h1>

<%= render 'form' %>

<%= link_to 'Back', comentarios_path %>

app/views/comentarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Placa:</strong>
  <%= @comentario.placa %>
</p>

<p>
  <strong>Coment:</strong>
  <%= @comentario.coment %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= @comentario.usuario %>
</p>

<p>
  <% if @comentario.buen_comentario == 1 %>
    <strong>Buen Comentario</strong>
  <% else %>
    <strong>Mal Comentario</strong>
  <% end %>
</p>

<%= link_to 'Edit', edit_comentario_path(@comentario) %> |
<%= link_to 'Back', comentarios_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TaxiComentarios</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/placas/_form.html.erb
<%= form_for(@placa) do |f| %>
  <% if @placa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@placa.errors.count, "error") %> prohibited this placa from being saved:</h2>

      <ul>
      <% @placa.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :numero %><br>
    <%= f.text_field :numero %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/placas/edit.html.erb
<h1>Editing placa</h1>

<%= render 'form' %>

<%= link_to 'Show', @placa %> |
<%= link_to 'Back', placas_path %>

app/views/placas/index.html.erb
<h1>Listing placas</h1>

<table>
  <thead>
    <tr>
      <th>Numero</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @placas.each do |placa| %>
      <tr>
        <td><%= placa.numero %></td>
        <td><%= link_to 'Show', placa %></td>
        <td><%= link_to 'Edit', edit_placa_path(placa) %></td>
        <td><%= link_to 'Destroy', placa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Placa', new_placa_path %>

app/views/placas/new.html.erb
<h1>New placa</h1>

<%= render 'form' %>

<%= link_to 'Back', placas_path %>

app/views/placas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Numero:</strong>
  <%= @placa.numero %>
</p>

<% if @placa.comentarios.any? %>
  <h3> Comentarios </h3>
  <ol class="comentarios">
    <%= render @comentarios %>
  </ol>
<% end %>

<%= link_to 'Edit', edit_placa_path(@placa) %> |
<%= link_to 'Back', placas_path %>